-   id: spectral
    name: spectral scanner
    description: "Spectral: Automated Code Security for Modern Teams"
    language: system
    entry: bash -c  '$HOME/.spectral/spectral scan --unstaged'
    pass_filenames: false
