-   id: spectral
    name: spectral scanner
    description: "Spectral: Automated Code Security for Modern Teams"
    language: docker_image
    entry: SpectralOps/spectral
    pass_filenames: false
    args: ["spectral", "run"]
