-   id: spectral
    name: spectral scanner
    description: "Spectral: Automated Code Security for Modern Teams"
    language: system
    entry: $HOME/.spectral/spectral scan --unstaged
    pass_filenames: false
