-   id: spectral
    name: spectral scanner
    description: "Spectral: Breach Protection for Developers"
    language: docker_image
    entry: jondot/spectral
    pass_filenames: false
    args: ["spectral", "run"]
